DECLARE
    v_dept99 NUMBER();
BEGIN 
    SELECT COUNT(*) INSERT INTO v_dept99 WHERE dept_no=99;

    IF(v_dept99 = 0) THEN 
        INSERT INTO DEPART VALUES(99, 'TEMPORAL', 'TEMPORAL');    
    END IF;

    UPDATE EMPLE SET DEPT_NO = 99 WHERE DEPT_NO = 10;

    DELETE FROM DEPART WHERE DEPT_NO = 10;

    SELECT * FROM EMPLE WHERE DEPT_NO = 10;
END;
/